server:
  port: 9302

image_url: https://api.cospay.io/upload

channel: 73088886094000

spring:
  http:
    multipart:
      max-request-size: 100Mb
      max-file-size: 100Mb
  data:
    mongodb:
      uri: mongodb://admin:admin@47.100.116.120:9998/coinListenner

mybatis:
  type-aliases-package: com.blockgod.springcloud.domain
  mapper-locations: classpath:mapper/**/**.xml
  config-location: classpath:mybatis/mybatis-config.xml

mapper:
  mappers: TkMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



