

remote_url: http://47.101.47.200:9907/upload
image_url: http://47.101.47.200:9907

channel: 73088886094000
spring:
  http:
    multipart:
      max-request-size: 100Mb
      max-file-size: 100Mb
  data:
    mongodb:
      uri: mongodb://dcpay:hYocUIctcEIzZ3XDAyw5@192.168.1.14:27017/dcpay

